package:
  name: omegaplot
  version: "0.5.1"

source:
  fn: omegaplot-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/o/omegaplot/omegaplot-0.5.1.tar.gz
  md5: 05658b51a18c63b38f26905a63e45ee1

build:
  number: 0
  entry_points:
    - omegafig = oputil.omegafig:cmdline
    - omegamap = oputil.omegamap:cmdline

requirements:
  build:
    - numpy
    - py2cairo
    - python
    - setuptools
  run:
    - numpy
    - py2cairo
    - python

about:
  home: http://newton.cx/~peter/
  license: GPL
  summary: A better-than-publication-quality plotting library based on Cairo.
