package:
  name: omegaplot
  version: !!str 0.5

source:
  fn: omegaplot-0.5.tar.bz2
  url: https://pypi.python.org/packages/source/o/omegaplot/omegaplot-0.5.tar.gz
  md5: bd929ba46f24849dceb635bd5f44c3c6

build:
  number: 0
  entry_points:
    - omegafig = oputil.omegafig:cmdline
    - omegamap = oputil.omegamap:cmdline

requirements:
  build:
    - numpy
    - py2cairo
    - python
    - setuptools
  run:
    - numpy
    - py2cairo
    - python

about:
  home: http://newton.cx/~peter/
  license: GPL
